name: "Checks"

on: { push, pull_request, workflow_dispatch }

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix flake check -L
